#pylint: disable=C0103
#pylint: disable=C0301
#pylint: disable=C0302
#pylint: disable=W0611
"""
The following pylint warning were disabled:
C0103 Used when a name doesn't doesn't fit the naming convention associated to its type (constant, variable, class...).
C0301 line-too-long
C0302 too-many-lines
W0611 unused-import
"""
"""
This file is automatically generated from HxS.
Do not change something here.
"""

from hxs_core.support import textToOneLine
from hxs_core.support import toAreaInBrackets
from hxs_core.unit import Unit
from hxs_core.block import Block
from hxs_core.fields import FieldDiscretePositions
from hxs_core.fields import FieldAreaDelegated
from hxs_core.fields import FieldAreaExplicit
from hxs_core.fields import FieldAreaExplicitCell
from hxs_core.bit_fields import BitFieldData
from hxs_core.bit_fields import BitFieldEnum
from hxs_core.bit_fields import BitFieldPhysical
from hxs_core.hxs_values import HxsDataValue
from hxs_core.hxs_values import HxsEnumValue
from hxs_core.hxs_values import HxsPhysicalValue
from block_StoreBlk import BlockStoreBlk

class UnitWasmFpgaStore(Unit):
    '''
    Unit generated by Hardware/Software interface description (.hxs)
    '''

    def __init__(self, busAccessList, instanceName):
        super(UnitWasmFpgaStore, self).__init__(busAccessList, instanceName)
        self.blocks = []
        self._block_StoreBlk = BlockStoreBlk(self, self.busAccessList[0], 0, 0x000000, 0x000020, 'block_StoreBlk')
        self.blocks.append(self._block_StoreBlk)

    @property
    def block_StoreBlk(self):
        '''
        Name:  WebAssembly Store Block
        Description: This block describes the WebAssembly store block.
        Bus Description: 
        Bus Segment: 0
        Block Resets:
        Pwr, Power On Reset
        '''
        return self._block_StoreBlk
